---
swagger: "2.0"
info:
  description: "This is a sample server pancake server"
  version: "0.0.1"
  title: "Some Pancake"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "hogehoge"
basePath: "/v1"
tags:
- name: "pancake"
  description: "Everything about your Pancake"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /pancake:
    post:
      tags:
      - "pancake"
      summary: "Add a new pancake"
      description: ""
      operationId: "addPancake"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pancake object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/body"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/inline_response_200"
        405:
          description: "Invalid input"
      security:
      - petstore_auth:
        - "write:pancakes"
        - "read:pancakes"
      x-swagger-router-controller: "Pancake"
  /pancake/{pancakeId}:
    get:
      tags:
      - "pancake"
      summary: "Find pancake by ID"
      description: "Returns a single pancake"
      operationId: "getPancakeById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "pancakeId"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/inline_response_200"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pancake not found"
      security:
      - api_key: []
      x-swagger-router-controller: "Pancake"
    put:
      tags:
      - "pancake"
      summary: "Update an existing pancake"
      description: "Pancake updated"
      operationId: "updatePancake"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "pancakeId"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Pancake object that updated"
        required: true
        schema:
          $ref: "#/definitions/body_1"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pancake not found"
        405:
          description: "Validation exception"
      security:
      - petstore_auth:
        - "write:pancakes"
        - "read:pancakes"
      x-swagger-router-controller: "Pancake"
    delete:
      tags:
      - "pancake"
      summary: "Delete pancake by ID"
      description: "Delete a single pancake"
      operationId: "deletePancakeById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "pancakeId"
        in: "path"
        description: "ID of pancake to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pancake not found"
      security:
      - petstore_auth:
        - "write:pancakes"
        - "read:pancakes"
      x-swagger-router-controller: "Pancake"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://hogehoge.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pancakes: "modify pancake in your account"
      read:pancakes: "read your pancake"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Pancake:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      pancakeId:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Order"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
  body:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      pancakeId:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Order"
  inline_response_200:
    properties:
      id:
        type: "integer"
        format: "int64"
      pancakeId:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Order"
  body_1:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      pancakeId:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Order"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
